### ISSUE TITLE
Game Object collision event is not working / always active

### ISSUE THREAD

**Issue by 14cfirth** [Nate-Bill/SchoolProject1#17]
Collisions between current game objects are always active. Even with the back ground disabled. We may need to redo collisions for Objects

**Comment by Nate-Bill** [comment]
yes, this is due to self collisions as it checks with itself

**Comment by Nate-Bill** [comment]
fixed in https://github.com/Nate-Bill/SchoolProject1/commit/b716716c976ba475cdb32f0c0a81461109d45362
